export enum Actions {
  AddTodo_Request = "AddTodo_Request",
  AddTodo_Success = "AddTodo_Success",
  SetTodos = "setTodos",
  EditTodo = "editTodo",
  CheckTodo = "checkTodo",
  LoadTodos = "loadTodos",
  SetTmpTodo = "setTmpTodo",
  DeleteTodo = "deleteTodo",
  FilterTodos = "filterTodos",
  SearchTodos = "searchTodos",
  SetIsLoading = "setIsLoading",
  DeleteAllTodo = "deleteAllTodo",
  SetFilterTodos = "setFilterTodos",
  DeleteCheckTodo = "deleteCheckTodo",
}
