export enum Actions {
  AddTodo_Request = "AddTodo_Request",
  AddTodo_Success = "AddTodo_Success",
  SetTodos = "setTodos",
  EditTodo_Request = "editTodo_Request",
  EditTodo_Success = "editTodo_Success",
  CheckTodo_Request = "checkTodo_Request",
  CheckTodo_Success = "checkTodo_Success",
  LoadTodos = "loadTodos",
  SetTmpTodo = "setTmpTodo",
  DeleteTodo_Request = "deleteTodo_Request",
  DeleteTodo_Success = "deleteTodo_Success",
  FilterTodos = "filterTodos",
  SearchTodos = "searchTodos",
  SetIsLoading = "setIsLoading",
  DeleteAllTodo_Request = "deleteAllTodo_Request",
  DeleteAllTodo_Success = "deleteAllTodo_Success",
  SetFilterTodos = "setFilterTodos",
  DeleteCheckTodo_Request = "deleteCheckTodo_Request",
  DeleteCheckTodo_Success = "deleteCheckTodo_Success",
  SetCurrentTodo = "setCurrentTodo",
  GetCurrentTodo = "getCurrentTodo",
}
